spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot5?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: sa123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: xyz.fusheng.entity